/* ==========================================================================
   PoródNaMiarę.pl — i18n dla kreatora planu porodu i generatora PDF
   Architektura: dane kreatora ZAWSZE przechowują kanoniczny tekst polski
   (value="..."). Ten słownik tłumaczy WYŁĄCZNIE warstwę wyświetlania (UI)
   oraz generuje DRUGI, tłumaczony PDF dla rodzica — obok oryginalnego
   polskiego PDF dla personelu szpitala, który pozostaje bez zmian.
   ========================================================================== */
(function (global) {
  'use strict';

  // ---- 1. Tytuły sekcji PDF — dokładnie zgodne z tablicą SECTIONS w index.html ----
  var STEP_TITLES = {
    pl: ["Badania matki istotne dla noworodka","Warunki i miejsce porodu","Osoby obecne","Przygotowanie do porodu","Przebieg porodu — I i II okres","Łagodzenie bólu porodowego","Ochrona krocza, indukcja i łożysko","Cięcie cesarskie (gdyby było konieczne)","Opieka nad noworodkiem","Krew pępowinowa (bankowanie)","Gdyby dziecko wymagało opieki neonatologicznej","Profilaktyka witaminą K","Badania i profilaktyka noworodka","Szczepienia noworodka","Połóg i oddział położniczy"],
    en: ["Mother's test results relevant to the newborn","Birth conditions and place","People present","Preparing for birth","Labour — first and second stage","Pain relief in labour","Perineal protection, induction and placenta","Caesarean section (if it becomes necessary)","Newborn care","Cord blood (banking)","If the baby needs neonatal care","Vitamin K prophylaxis","Newborn screening and prophylaxis","Newborn vaccinations","Postpartum ward"],
    de: ["Für das Neugeborene relevante Befunde der Mutter","Bedingungen und Ort der Geburt","Anwesende Personen","Vorbereitung auf die Geburt","Geburtsverlauf — Eröffnungs- und Austreibungsphase","Schmerzlinderung während der Geburt","Dammschutz, Einleitung und Plazenta","Kaiserschnitt (falls nötig)","Versorgung des Neugeborenen","Nabelschnurblut (Banking)","Falls das Kind neonatologische Betreuung benötigt","Vitamin-K-Prophylaxe","Screening und Prophylaxe beim Neugeborenen","Impfungen des Neugeborenen","Wochenbett und Wochenbettstation"],
    uk: ["Результати обстежень матері, важливі для новонародженого","Умови та місце пологів","Присутні особи","Підготовка до пологів","Перебіг пологів — I та II період","Знеболення під час пологів","Захист промежини, індукція та послід","Кесарів розтин (якщо буде потрібен)","Догляд за новонародженим","Пуповинна кров (банкування)","Якщо дитині знадобиться неонатальна допомога","Профілактика вітаміном K","Обстеження та профілактика новонародженого","Щеплення новонародженого","Післяпологовий період і відділення"],
    ru: ["Результаты обследований матери, важные для новорождённого","Условия и место родов","Присутствующие лица","Подготовка к родам","Течение родов — I и II период","Обезболивание родов","Защита промежности, индукция и плацента","Кесарево сечение (если понадобится)","Уход за новорождённым","Пуповинная кровь (банкирование)","Если ребёнку понадобится неонатальная помощь","Профилактика витамином K","Обследование и профилактика новорождённого","Прививки новорождённого","Послеродовой период и отделение"]
  };

  // ---- 1b. Etykiety pól danych (rows) na stronie z danymi kluczowymi ----
  var ROW_LABELS = {
    pl: {"Rodząca":"Rodząca","Osoba towarzysząca":"Osoba towarzysząca","Termin porodu":"Termin porodu","Lekarz / położna":"Lekarz / położna","Grupa krwi i Rh":"Grupa krwi i Rh","HBsAg matki":"HBsAg matki","GBS":"GBS"},
    en: {"Rodząca":"Mother","Osoba towarzysząca":"Support person","Termin porodu":"Due date","Lekarz / położna":"Doctor / midwife","Grupa krwi i Rh":"Blood group and Rh","HBsAg matki":"Mother's HBsAg","GBS":"GBS"},
    de: {"Rodząca":"Mutter","Osoba towarzysząca":"Begleitperson","Termin porodu":"Geburtstermin","Lekarz / położna":"Arzt / Hebamme","Grupa krwi i Rh":"Blutgruppe und Rh","HBsAg matki":"HBsAg der Mutter","GBS":"GBS"},
    uk: {"Rodząca":"Породілля","Osoba towarzysząca":"Особа супроводу","Termin porodu":"Дата пологів","Lekarz / położna":"Лікар / акушерка","Grupa krwi i Rh":"Група крові та Rh","HBsAg matki":"HBsAg матері","GBS":"СГБ"},
    ru: {"Rodząca":"Роженица","Osoba towarzysząca":"Сопровождающий","Termin porodu":"Дата родов","Lekarz / położna":"Врач / акушерка","Grupa krwi i Rh":"Группа крови и Rh","HBsAg matki":"HBsAg матери","GBS":"СГБ"}
  };

  // ---- 1c. Nagłówki H2 13 kroków UI kreatora (inne niż tytuły sekcji PDF!) ----
  var UI_STEP_TITLES = {
    pl: ["Dane i informacje kluczowe","Warunki i miejsce porodu","Osoba towarzysząca i osoby obecne","Przygotowanie do porodu","Przebieg porodu — I i II okres","Łagodzenie bólu porodowego","Ochrona krocza, indukcja i łożysko","Gdyby konieczne było cięcie cesarskie","Opieka nad noworodkiem","Profilaktyka i badania noworodka","Szczepienia noworodka","Połóg i oddział położniczy","Podsumowanie Waszego planu"],
    en: ["Key details","Birth conditions and place","Support person and people present","Preparing for birth","Labour — first and second stage","Pain relief in labour","Perineal protection, induction and placenta","If a caesarean section becomes necessary","Newborn care","Newborn screening and prophylaxis","Newborn vaccinations","Postpartum ward","Summary of your plan"],
    de: ["Wichtige Angaben","Bedingungen und Ort der Geburt","Begleitperson und Anwesende","Vorbereitung auf die Geburt","Geburtsverlauf — Eröffnungs- und Austreibungsphase","Schmerzlinderung während der Geburt","Dammschutz, Einleitung und Plazenta","Falls ein Kaiserschnitt nötig wird","Versorgung des Neugeborenen","Screening und Prophylaxe des Neugeborenen","Impfungen des Neugeborenen","Wochenbett und Wochenbettstation","Zusammenfassung Ihres Plans"],
    uk: ["Ключові дані","Умови та місце пологів","Особа супроводу та присутні","Підготовка до пологів","Перебіг пологів — I та II період","Знеболення під час пологів","Захист промежини, індукція та послід","Якщо знадобиться кесарів розтин","Догляд за новонародженим","Профілактика та обстеження новонародженого","Щеплення новонародженого","Післяпологовий період і відділення","Підсумок вашого плану"],
    ru: ["Ключевые данные","Условия и место родов","Сопровождающий и присутствующие","Подготовка к родам","Течение родов — I и II период","Обезболивание родов","Защита промежности, индукция и плацента","Если понадобится кесарево сечение","Уход за новорождённым","Профилактика и обследование новорождённого","Прививки новорождённого","Послеродовой период и отделение","Итоги вашего плана"]
  };

  // ---- 2. UI kreatora (nawigacja, przyciski, etykiety) ----------------
  var UI = {
    pl: {back:"← Wstecz", next:"Dalej →", download:"Pobierz plan porodu (PDF)", downloadPl:"Pobierz PDF po polsku (dla personelu)", downloadTranslated:"Pobierz PDF w Twoim języku (dla siebie)", step:"Krok", of:"z", langLabel:"Język", preparing:"Przygotowuję dokument…", note:"Dokument dla personelu jest zawsze po polsku — to on musi go zrozumieć w kilka sekund.",
      previewTag:"podgląd", planFallback:"Nasze dziecko", planPrefix:"Plan porodu — ", term:"Przewidywany termin", priorityLabel:"Priorytet nadrzędny:", priorityText:"zdrowie i życie dziecka oraz mamy są bezwzględnym priorytetem, nadrzędnym wobec każdego punktu planu.", emptyState:"Zaznacz opcje w kolejnych krokach, aby zobaczyć podgląd planu.", lockedRemaining:"Pozostałe", lockedIn:"pozycji w", lockedSections:"sekcjach", lockedDesc:"Pełny, profesjonalnie sformatowany plan PDF odblokujesz po zakupie pakietu.", lockedCta:"Odblokuj pełny plan →", previewFooter:"To tylko podgląd. Gotowy dokument PDF — z brandem, formatowaniem, miejscem na podpisy i datę — pobierzesz po zakupie."},
    en: {back:"← Back", next:"Next →", download:"Download birth plan (PDF)", downloadPl:"Download Polish PDF (for hospital staff)", downloadTranslated:"Download PDF in English (for yourself)", step:"Step", of:"of", langLabel:"Language", preparing:"Preparing document…", note:"The staff document is always in Polish — they need to understand it in seconds.",
      previewTag:"preview", planFallback:"Our baby", planPrefix:"Birth plan — ", term:"Expected due date", priorityLabel:"Overriding priority:", priorityText:"the health and life of the baby and mother are an absolute priority, taking precedence over every point of the plan.", emptyState:"Select options in the next steps to see a preview of your plan.", lockedRemaining:"Remaining", lockedIn:"items in", lockedSections:"sections", lockedDesc:"Unlock the full, professionally formatted PDF plan after buying a package.", lockedCta:"Unlock the full plan →", previewFooter:"This is just a preview. You'll download the finished PDF — with branding, formatting, and space for signatures and date — after purchase."},
    de: {back:"← Zurück", next:"Weiter →", download:"Geburtsplan herunterladen (PDF)", downloadPl:"Polnisches PDF herunterladen (für das Klinikpersonal)", downloadTranslated:"PDF auf Deutsch herunterladen (für Sie selbst)", step:"Schritt", of:"von", langLabel:"Sprache", preparing:"Dokument wird vorbereitet…", note:"Das Dokument für das Personal ist immer auf Polnisch — es muss es in Sekunden verstehen.",
      previewTag:"Vorschau", planFallback:"Unser Baby", planPrefix:"Geburtsplan — ", term:"Voraussichtlicher Geburtstermin", priorityLabel:"Übergeordnete Priorität:", priorityText:"Gesundheit und Leben von Kind und Mutter haben absoluten Vorrang vor jedem Punkt des Plans.", emptyState:"Wählen Sie in den nächsten Schritten Optionen aus, um eine Vorschau Ihres Plans zu sehen.", lockedRemaining:"Verbleibende", lockedIn:"Punkte in", lockedSections:"Abschnitten", lockedDesc:"Schalten Sie den vollständigen, professionell formatierten PDF-Plan nach dem Kauf eines Pakets frei.", lockedCta:"Vollständigen Plan freischalten →", previewFooter:"Dies ist nur eine Vorschau. Das fertige PDF — mit Branding, Formatierung und Platz für Unterschriften und Datum — erhalten Sie nach dem Kauf."},
    uk: {back:"← Назад", next:"Далі →", download:"Завантажити план пологів (PDF)", downloadPl:"Завантажити PDF польською (для персоналу)", downloadTranslated:"Завантажити PDF українською (для себе)", step:"Крок", of:"з", langLabel:"Мова", preparing:"Готуємо документ…", note:"Документ для персоналу завжди польською — його мають зрозуміти за кілька секунд.",
      previewTag:"перегляд", planFallback:"Наша дитина", planPrefix:"План пологів — ", term:"Очікувана дата пологів", priorityLabel:"Найвищий пріоритет:", priorityText:"здоров'я і життя дитини та мами є абсолютним пріоритетом, що переважає над кожним пунктом плану.", emptyState:"Позначте опції в наступних кроках, щоб побачити перегляд плану.", lockedRemaining:"Залишилось", lockedIn:"пунктів у", lockedSections:"розділах", lockedDesc:"Повний, професійно відформатований PDF-план розблокуєте після покупки пакета.", lockedCta:"Розблокувати повний план →", previewFooter:"Це лише перегляд. Готовий PDF-документ — з брендуванням, форматуванням, місцем для підписів і дати — завантажите після покупки."},
    ru: {back:"← Назад", next:"Далее →", download:"Скачать план родов (PDF)", downloadPl:"Скачать PDF на польском (для персонала)", downloadTranslated:"Скачать PDF на русском (для себя)", step:"Шаг", of:"из", langLabel:"Язык", preparing:"Готовим документ…", note:"Документ для персонала всегда на польском — его должны понять за несколько секунд.",
      previewTag:"просмотр", planFallback:"Наш ребёнок", planPrefix:"План родов — ", term:"Предполагаемая дата родов", priorityLabel:"Наивысший приоритет:", priorityText:"здоровье и жизнь ребёнка и мамы являются абсолютным приоритетом, преобладающим над каждым пунктом плана.", emptyState:"Отметьте опции в следующих шагах, чтобы увидеть предпросмотр плана.", lockedRemaining:"Осталось", lockedIn:"пунктов в", lockedSections:"разделах", lockedDesc:"Полный, профессионально оформленный PDF-план разблокируете после покупки пакета.", lockedCta:"Разблокировать полный план →", previewFooter:"Это только предпросмотр. Готовый PDF-документ — с брендингом, форматированием, местом для подписей и даты — скачаете после покупки."}
  };

  // ---- 3. Statyczne etykiety PDF (okładka, nagłówki, stopka) ----------
  var PDF_STATIC = {
    pl: {cover:"PLAN PORODU", brand:"PorodNaMiare.pl", parents:"Rodzice", term:"Przewidywany termin", footerNote:"Dokument organizacyjny — nie zastępuje porady lekarskiej.", standard:"Zgodny ze Standardem Opieki Okołoporodowej — Dz.U. 2025 poz. 1525",
      priority:"PRIORYTET NADRZĘDNY: zdrowie i życie dziecka oraz matki są bezwzględnym priorytetem, nadrzędnym wobec każdego punktu tego planu. W sytuacji zagrożenia akceptujemy wszystkie niezbędne interwencje medyczne. Prosimy jedynie o możliwie szybką informację o sytuacji.",
      signTitle:"Oświadczenie i podpisy", signText:"Świadomie wyrażamy powyższe preferencje. Akceptujemy wszelkie niezbędne interwencje ratujące zdrowie i życie dziecka oraz matki.", signMother:"Matka", signFather:"Ojciec / osoba towarzysząca", signDate:"Data"},
    en: {cover:"BIRTH PLAN", brand:"PorodNaMiare.pl", parents:"Parents", term:"Expected due date", footerNote:"Organisational document — does not replace medical advice. Original Polish document remains the binding version for hospital staff.", standard:"Compliant with the Polish Perinatal Care Standard — Journal of Laws 2025, item 1525",
      priority:"OVERRIDING PRIORITY: the health and life of the baby and the mother are an absolute priority, taking precedence over every point of this plan. In an emergency we accept all necessary medical interventions. We only ask to be informed of the situation as promptly as possible.",
      signTitle:"Declaration and signatures", signText:"We knowingly express the above preferences. We accept all interventions necessary to save the life and health of the baby and the mother.", signMother:"Mother", signFather:"Father / support person", signDate:"Date"},
    de: {cover:"GEBURTSPLAN", brand:"PorodNaMiare.pl", parents:"Eltern", term:"Voraussichtlicher Geburtstermin", footerNote:"Organisatorisches Dokument — ersetzt keine ärztliche Beratung. Das polnische Originaldokument bleibt für das Klinikpersonal maßgeblich.", standard:"Konform mit dem polnischen Standard der perinatalen Versorgung — GBl. 2025 Pos. 1525",
      priority:"ÜBERGEORDNETE PRIORITÄT: Gesundheit und Leben von Kind und Mutter haben absoluten Vorrang vor jedem Punkt dieses Plans. Im Notfall akzeptieren wir alle notwendigen medizinischen Maßnahmen. Wir bitten lediglich um möglichst rasche Information über die Situation.",
      signTitle:"Erklärung und Unterschriften", signText:"Wir äußern die obigen Präferenzen bewusst. Wir akzeptieren alle Maßnahmen, die zur Rettung von Leben und Gesundheit von Kind und Mutter notwendig sind.", signMother:"Mutter", signFather:"Vater / Begleitperson", signDate:"Datum"},
    uk: {cover:"ПЛАН ПОЛОГІВ", brand:"PorodNaMiare.pl", parents:"Батьки", term:"Очікувана дата пологів", footerNote:"Організаційний документ — не замінює консультацію лікаря. Оригінальний польський документ залишається основним для персоналу лікарні.", standard:"Відповідає польському Стандарту перинатальної допомоги — Dz.U. 2025 поз. 1525",
      priority:"НАЙВИЩИЙ ПРІОРИТЕТ: здоров'я і життя дитини та матері є абсолютним пріоритетом, що переважає над кожним пунктом цього плану. У разі загрози ми погоджуємось на всі необхідні медичні втручання. Просимо лише про якнайшвидше інформування про ситуацію.",
      signTitle:"Заява та підписи", signText:"Свідомо висловлюємо вищезазначені побажання. Погоджуємось на всі втручання, необхідні для порятунку життя і здоров'я дитини та матері.", signMother:"Мати", signFather:"Батько / особа супроводу", signDate:"Дата"},
    ru: {cover:"ПЛАН РОДОВ", brand:"PorodNaMiare.pl", parents:"Родители", term:"Предполагаемая дата родов", footerNote:"Организационный документ — не заменяет консультацию врача. Оригинальный польский документ остаётся основным для персонала больницы.", standard:"Соответствует польскому Стандарту перинатальной помощи — Dz.U. 2025 поз. 1525",
      priority:"НАИВЫСШИЙ ПРИОРИТЕТ: здоровье и жизнь ребёнка и матери являются абсолютным приоритетом, преобладающим над каждым пунктом этого плана. В случае угрозы мы соглашаемся на все необходимые медицинские вмешательства. Просим лишь о максимально быстром информировании о ситуации.",
      signTitle:"Заявление и подписи", signText:"Осознанно выражаем вышеуказанные пожелания. Согласны на все вмешательства, необходимые для спасения жизни и здоровья ребёнка и матери.", signMother:"Мать", signFather:"Отец / сопровождающий", signDate:"Дата"}
  };

  // ---- 4. Słownik 96 fraz klinicznych/preferencji (PL -> EN/DE/UK) ----
  // Klucz = dokładny polski tekst z value="" w kreatorze (canonical).
  var VALUES = {
    "Krocze ogolę samodzielnie w domu przed przyjazdem do szpitala": {en:"I will shave the perineal area myself at home before coming to hospital", de:"Den Intimbereich rasiere ich vor der Ankunft in der Klinik selbst zu Hause", uk:"Ділянку промежини поголю самостійно вдома перед приїздом до лікарні", ru:"Промежность выбрею самостоятельно дома перед приездом в больницу"},
    "Proszę o instruktaż położnej podczas parcia, aby chronić krocze": {en:"Please have the midwife guide me during pushing to protect the perineum", de:"Bitte Anleitung durch die Hebamme beim Pressen, um den Damm zu schützen", uk:"Прошу інструктаж акушерки під час потуг, щоб захистити промежину", ru:"Прошу инструктаж акушерки во время потуг, чтобы защитить промежность"},
    "Przy żółtaczce — pomiar bilirubiny i ewentualna fototerapia przy mamie, z zachowaniem karmienia piersią": {en:"If jaundice occurs — bilirubin measurement and any phototherapy at the mother's side, continuing breastfeeding", de:"Bei Gelbsucht — Bilirubinmessung und eine etwaige Fototherapie am Bett der Mutter, unter Fortführung des Stillens", uk:"При жовтяниці — вимірювання білірубіну та можлива фототерапія поряд з мамою, зі збереженням грудного вигодовування", ru:"При желтухе — измерение билирубина и возможная фототерапия рядом с мамой, с сохранением грудного вскармливания"},
    "Przy hipoglikemii najpierw dokarmienie siarą lub odciągniętym mlekiem matki; mleko modyfikowane tylko na wskazanie lekarskie": {en:"For hypoglycaemia, supplement first with colostrum or expressed breast milk; formula only on medical indication", de:"Bei Hypoglykämie zuerst mit Kolostrum oder abgepumpter Muttermilch zufüttern; Formulanahrung nur bei medizinischer Indikation", uk:"При гіпоглікемії спершу догодовування молозивом або зцідженим молоком матері; суміш лише за медичними показаннями", ru:"При гипогликемии сначала докорм молозивом или сцеженным молоком матери; смесь только по медицинским показаниям"},
    "Codzienne badanie pediatryczne dziecka w obecności rodzica, z omówieniem wyników i zaleceń": {en:"Daily paediatric examination of the baby in a parent's presence, with the findings and recommendations explained to us", de:"Tägliche pädiatrische Untersuchung des Kindes im Beisein eines Elternteils, mit Erläuterung der Befunde und Empfehlungen", uk:"Щоденний педіатричний огляд дитини в присутності одного з батьків, з поясненням результатів і рекомендацій", ru:"Ежедневный педиатрический осмотр ребёнка в присутствии родителя, с обсуждением результатов и рекомендаций"},
    "Regularna ocena nasilenia bólu w połogu i jego skuteczne łagodzenie": {en:"Regular assessment of pain intensity in the postpartum period and its effective relief", de:"Regelmäßige Einschätzung der Schmerzintensität im Wochenbett und wirksame Schmerzlinderung", uk:"Регулярна оцінка інтенсивності болю в післяпологовому періоді та його ефективне полегшення", ru:"Регулярная оценка интенсивности боли в послеродовом периоде и её эффективное облегчение"},
    "Pisemna informacja o prawie do wizyt patronażowych położnej POZ wraz z danymi kontaktowymi": {en:"Written information about the right to community-midwife postnatal (patronage) visits, including contact details", de:"Schriftliche Information über das Recht auf Nachsorgebesuche der Gemeindehebamme, einschließlich Kontaktdaten", uk:"Письмова інформація про право на патронажні візити акушерки первинної ланки із контактними даними", ru:"Письменная информация о праве на патронажные посещения участковой акушерки с контактными данными"},
"dziewczynka": {en:"girl", de:"Mädchen", uk:"дівчинка", ru:"девочка"},
"chłopiec": {en:"boy", de:"Junge", uk:"хлопчик", ru:"мальчик"},
"HBsAg matki: ujemny (odroczenie WZW B bezpieczne)": {en:"Mother's HBsAg: negative (safe to delay hepatitis B vaccination)", de:"HBsAg der Mutter: negativ (Aufschub der Hepatitis-B-Impfung sicher)", uk:"HBsAg матері: негативний (відкладення щеплення від гепатиту B безпечне)", ru:"HBsAg матери: отрицательный (отсрочка прививки от гепатита B безопасна)"},
"HBsAg matki: dodatni — postępowanie szczepienne do omówienia z neonatologiem": {en:"Mother's HBsAg: positive — vaccination protocol to be discussed with the neonatologist", de:"HBsAg der Mutter: positiv — Impfvorgehen mit dem Neonatologen zu besprechen", uk:"HBsAg матері: позитивний — схему щеплення обговорити з неонатологом", ru:"HBsAg матери: положительный — схему вакцинации обсудить с неонатологом"},
"HBsAg matki: wynik nieznany — do omówienia z neonatologiem": {en:"Mother's HBsAg: result unknown — to be discussed with the neonatologist", de:"HBsAg der Mutter: Ergebnis unbekannt — mit dem Neonatologen zu besprechen", uk:"HBsAg матері: результат невідомий — обговорити з неонатологом", ru:"HBsAg матери: результат неизвестен — обсудить с неонатологом"},
"GBS: ujemny": {en:"GBS: negative", de:"GBS: negativ", uk:"СГБ: негативний", ru:"СГБ: отрицательный"},
"GBS: dodatni — profilaktyka antybiotykowa przy porodzie": {en:"GBS: positive — antibiotic prophylaxis during labour", de:"GBS: positiv — Antibiotikaprophylaxe während der Geburt", uk:"СГБ: позитивний — антибіотикопрофілактика під час пологів", ru:"СГБ: положительный — антибиотикопрофилактика во время родов"},
"GBS: nieznany": {en:"GBS: unknown", de:"GBS: unbekannt", uk:"СГБ: невідомий", ru:"СГБ: неизвестен"},
"Chciałabym rodzić w sali pojedynczej": {en:"I would like to give birth in a single room", de:"Ich möchte in einem Einzelzimmer entbinden", uk:"Хочу народжувати в окремій палаті", ru:"Хочу рожать в отдельной палате"},
"Chciałabym, by w sali była toaleta": {en:"I would like the room to have a private bathroom", de:"Ich möchte, dass sich im Zimmer eine Toilette befindet", uk:"Хочу, щоб у палаті був туалет", ru:"Хочу, чтобы в палате был туалет"},
"Mogę rodzić na sali wieloosobowej": {en:"I am comfortable giving birth in a shared room", de:"Ich kann auch in einem Mehrbettzimmer entbinden", uk:"Можу народжувати в загальній палаті", ru:"Могу рожать в общей палате"},
"Chciałabym rodzić we własnym ubraniu": {en:"I would like to give birth in my own clothes", de:"Ich möchte in meiner eigenen Kleidung entbinden", uk:"Хочу народжувати у власному одязі", ru:"Хочу рожать в собственной одежде"},
"Zależy mi na dostępie do prysznica lub wanny w sali": {en:"Access to a shower or bath in the room is important to me", de:"Mir ist der Zugang zu Dusche oder Wanne im Zimmer wichtig", uk:"Для мене важливий доступ до душу або ванни в палаті", ru:"Для меня важен доступ к душу или ванне в палате"},
"Przyciemnione światło i cisza w sali porodowej": {en:"Dimmed lighting and quiet in the delivery room", de:"Gedämpftes Licht und Ruhe im Kreißsaal", uk:"Приглушене світло і тиша в пологовій залі", ru:"Приглушённый свет и тишина в родильном зале"},
"Możliwość słuchania własnej muzyki podczas porodu": {en:"The option to listen to my own music during labour", de:"Möglichkeit, während der Geburt eigene Musik zu hören", uk:"Можливість слухати власну музику під час пологів", ru:"Возможность слушать свою музыку во время родов"},
"Możliwość robienia zdjęć podczas porodu i pierwszych chwil (za zgodą personelu)": {en:"The option to take photos during labour and the first moments (with staff consent)", de:"Möglichkeit, während der Geburt und den ersten Momenten zu fotografieren (mit Zustimmung des Personals)", uk:"Можливість фотографувати під час пологів і перших миттєвостей (за згодою персоналу)", ru:"Возможность фотографировать во время родов и первых мгновений (с согласия персонала)"},
"Możliwość nagrywania wideo podczas porodu i pierwszych chwil (za zgodą personelu)": {en:"The option to film during labour and the first moments (with staff consent)", de:"Möglichkeit, während der Geburt und den ersten Momenten zu filmen (mit Zustimmung des Personals)", uk:"Можливість знімати відео під час пологів і перших миттєвостей (за згодою персоналу)", ru:"Возможность снимать видео во время родов и первых мгновений (с согласия персонала)"},
"Chcę rodzić z osobą bliską (ojcem dziecka / partnerem)": {en:"I want to give birth with a support person (the baby's father / my partner)", de:"Ich möchte mit einer Begleitperson entbinden (Vater des Kindes / Partner)", uk:"Хочу народжувати з близькою людиною (батьком дитини / партнером)", ru:"Хочу рожать с близким человеком (отцом ребёнка / партнёром)"},
"Obecność obojga rodziców przy wszystkich badaniach i zabiegach": {en:"Both parents present at all examinations and procedures", de:"Anwesenheit beider Elternteile bei allen Untersuchungen und Eingriffen", uk:"Присутність обох батьків на всіх обстеженнях і процедурах", ru:"Присутствие обоих родителей на всех обследованиях и процедурах"},
"Jeśli matka nie może być obecna — przy zabiegach obecny jest ojciec dziecka": {en:"If the mother cannot be present, the baby's father attends procedures instead", de:"Falls die Mutter nicht anwesend sein kann, ist der Vater des Kindes bei Eingriffen anwesend", uk:"Якщо мати не може бути присутньою — на процедурах присутній батько дитини", ru:"Если мать не может присутствовать — на процедурах присутствует отец ребёнка"},
"Prosimy o bieżące informowanie osoby towarzyszącej o postępie porodu": {en:"Please keep the support person continuously informed of labour progress", de:"Wir bitten um laufende Information der Begleitperson über den Geburtsfortschritt", uk:"Просимо постійно інформувати особу супроводу про перебіг пологів", ru:"Просим постоянно информировать сопровождающего о ходе родов"},
"Obecne tylko niezbędne osoby z personelu": {en:"Only essential staff members present", de:"Nur unbedingt notwendiges Personal anwesend", uk:"Присутні лише необхідні співробітники персоналу", ru:"Присутствуют только необходимые сотрудники персонала"},
"Zgoda na obecność studentów/-ek położnictwa i medycyny": {en:"Consent for midwifery/medical students to be present", de:"Zustimmung zur Anwesenheit von Hebammen- und Medizinstudierenden", uk:"Згода на присутність студентів акушерства та медицини", ru:"Согласие на присутствие студентов акушерства и медицины"},
"W miarę możliwości ta sama położna przez cały poród": {en:"The same midwife throughout labour, where possible", de:"Nach Möglichkeit dieselbe Hebamme während der gesamten Geburt", uk:"За можливості — одна акушерка протягом усіх пологів", ru:"По возможности — одна акушерка на протяжении всех родов"},
"Bez zabiegów przygotowujących (lewatywa, golenie), chyba że o nie poproszę": {en:"No preparatory procedures (enema, shaving) unless I request them", de:"Keine vorbereitenden Maßnahmen (Einlauf, Rasur), außer ich bitte darum", uk:"Без підготовчих процедур (клізма, гоління), якщо я сама про них не попрошу", ru:"Без подготовительных процедур (клизма, бритьё), если я сама об этом не попрошу"},
"Proszę o lewatywę przy przyjęciu": {en:"Please give me an enema on admission", de:"Bitte einen Einlauf bei der Aufnahme", uk:"Прошу зробити клізму при поступленні", ru:"Прошу сделать клизму при поступлении"},
"Zgoda na założenie wenflonu przy przyjęciu": {en:"Consent to an IV cannula on admission", de:"Zustimmung zum Legen einer Venenverweilkanüle bei der Aufnahme", uk:"Згода на встановлення внутрішньовенного катетера при поступленні", ru:"Согласие на установку внутривенного катетера при поступлении"},
"Bez wenflonu, chyba że wystąpi konieczność podania leków dożylnie (akceptujemy założenie w razie wskazań)": {en:"No IV cannula unless intravenous medication becomes necessary (we accept it if medically indicated)", de:"Keine Venenverweilkanüle, außer eine intravenöse Medikamentengabe wird notwendig (wir akzeptieren sie bei medizinischer Indikation)", uk:"Без внутрішньовенного катетера, якщо не виникне потреба у введенні ліків внутрішньовенно (погоджуємось за наявності показань)", ru:"Без катетера, если не возникнет необходимость введения препаратов внутривенно (согласны на установку при наличии показаний)"},
"Możliwość jedzenia i picia w trakcie porodu, o ile nie ma przeciwwskazań": {en:"The option to eat and drink during labour, if not contraindicated", de:"Möglichkeit, während der Geburt zu essen und zu trinken, sofern keine Gegenanzeigen bestehen", uk:"Можливість їсти та пити під час пологів, якщо немає протипоказань", ru:"Возможность есть и пить во время родов, если нет противопоказаний"},
"Pełna i bieżąca informacja o postępie porodu": {en:"Full, ongoing information about labour progress", de:"Vollständige, laufende Information über den Geburtsfortschritt", uk:"Повна й постійна інформація про перебіг пологів", ru:"Полная и постоянная информация о ходе родов"},
"Zależy mi na porodzie o przebiegu naturalnym (fizjologicznym)": {en:"A natural (physiological) birth is important to me", de:"Mir ist eine natürliche (physiologische) Geburt wichtig", uk:"Для мене важливі природні (фізіологічні) пологи", ru:"Для меня важны естественные (физиологические) роды"},
"Pytanie o zgodę na badania i zabiegi poza sytuacjami nagłymi": {en:"Please ask for my consent before examinations and procedures, except in emergencies", de:"Bitte um Zustimmung vor Untersuchungen und Eingriffen, außer in Notfällen", uk:"Просимо питати згоду перед обстеженнями та процедурами, крім невідкладних ситуацій", ru:"Просим спрашивать согласие перед обследованиями и процедурами, кроме экстренных ситуаций"},
"Oksytocyna, amniotomia, stałe KTG — tylko po wyjaśnieniu wskazań i mojej zgodzie": {en:"Oxytocin, amniotomy, continuous CTG — only after explanation of indications and my consent", de:"Oxytocin, Amniotomie, kontinuierliches CTG — nur nach Erklärung der Indikation und meiner Zustimmung", uk:"Окситоцин, амніотомія, постійний КТГ — лише після пояснення показань і моєї згоди", ru:"Окситоцин, амниотомия, постоянный КТГ — только после объяснения показаний и моего согласия"},
"Swoboda wydawania dźwięków podczas porodu": {en:"Freedom to vocalise during labour", de:"Freiheit, während der Geburt Laute zu äußern", uk:"Свобода видавати звуки під час пологів", ru:"Свобода издавать звуки во время родов"},
"Możliwość korzystania z gwizdka porodowego (wsparcie kontrolowanego oddechu i parcia)": {en:"The option to use a birth whistle (supports controlled breathing and pushing)", de:"Möglichkeit, eine Geburtspfeife zu nutzen (unterstützt kontrolliertes Atmen und Pressen)", uk:"Можливість використовувати пологовий свисток (підтримка контрольованого дихання й потуг)", ru:"Возможность использовать родовой свисток (поддержка контролируемого дыхания и потуг)"},
"Ograniczenie badań dopochwowych do niezbędnego minimum": {en:"Vaginal examinations limited to the necessary minimum", de:"Vaginaluntersuchungen auf das notwendige Minimum beschränkt", uk:"Обмеження вагінальних оглядів до необхідного мінімуму", ru:"Ограничение влагалищных осмотров до необходимого минимума"},
"Swoboda ruchu i dowolne pozycje; dostęp do wanny/prysznica, drabinki, worka sako": {en:"Freedom of movement and choice of positions; access to bath/shower, birthing ladder, birthing ball", de:"Bewegungsfreiheit und freie Positionswahl; Zugang zu Wanne/Dusche, Gebärleiter, Gymnastikball", uk:"Свобода руху та вибір поз; доступ до ванни/душу, драбини, фітболу", ru:"Свобода движения и любые позиции; доступ к ванне/душу, лестнице, фитболу"},
"Wybór pozycji w II okresie (w tym pionowej), parcie spontaniczne": {en:"Choice of position in the second stage (including upright), spontaneous pushing", de:"Positionswahl in der Austreibungsphase (auch aufrecht), spontanes Pressen", uk:"Вибір положення у другому періоді (у тому числі вертикального), спонтанні потуги", ru:"Выбор положения во втором периоде (в том числе вертикального), спонтанные потуги"},
"Brak zgody na masaż szyjki i chwyt Kristellera": {en:"No consent to cervical massage or Kristeller manoeuvre (fundal pressure)", de:"Keine Zustimmung zu Zervixmassage und Kristeller-Handgriff", uk:"Немає згоди на масаж шийки матки та прийом Крістеллера", ru:"Нет согласия на массаж шейки матки и приём Кристеллера"},
"Przygaszone światło i cisza w momencie narodzin": {en:"Dimmed lighting and quiet at the moment of birth", de:"Gedämpftes Licht und Ruhe im Moment der Geburt", uk:"Приглушене світло і тиша в момент народження", ru:"Приглушённый свет и тишина в момент рождения"},
"W pierwszej kolejności metody niefarmakologiczne: immersja wodna, pozycje, masaż, TENS, techniki oddechowe": {en:"Non-pharmacological methods first: water immersion, positions, massage, TENS, breathing techniques", de:"Zuerst nichtmedikamentöse Methoden: Wasserimmersion, Positionswechsel, Massage, TENS, Atemtechniken", uk:"Спочатку нефармакологічні методи: занурення у воду, положення тіла, масаж, ТЕНС, дихальні техніки", ru:"В первую очередь немедикаментозные методы: погружение в воду, положения тела, массаж, ТЕНС, дыхательные техники"},
"Proszę nie proponować środków farmakologicznych, zanim sama o nie poproszę": {en:"Please do not offer pharmacological pain relief unless I ask for it", de:"Bitte keine medikamentöse Schmerzlinderung anbieten, bevor ich selbst danach frage", uk:"Прошу не пропонувати фармакологічне знеболення, поки я сама не попрошу", ru:"Прошу не предлагать медикаментозные средства обезболивания, пока я сама об этом не попрошу"},
"Analgezja wziewna (mieszanina podtlenku azotu z tlenem)": {en:"Inhaled analgesia (nitrous oxide and oxygen mixture)", de:"Inhalationsanalgesie (Lachgas-Sauerstoff-Gemisch)", uk:"Інгаляційна анальгезія (суміш закису азоту з киснем)", ru:"Ингаляционная анальгезия (смесь закиси азота с кислородом)"},
"Znieczulenie zewnątrzoponowe (EDA), jeśli o nie poproszę": {en:"Epidural anaesthesia (EDA), if I request it", de:"Periduralanästhesie (PDA), falls ich danach frage", uk:"Епідуральна анестезія (ЕДА), якщо я про неї попрошу", ru:"Эпидуральная анестезия (ЭДА), если я об этом попрошу"},
"Analgezja remifentanylem w systemie PCA, jeśli o nią poproszę lub EDA będzie niedostępne/przeciwwskazane": {en:"Remifentanil PCA analgesia, if I request it or if an epidural is unavailable/contraindicated", de:"Remifentanil-PCA-Analgesie, falls ich danach frage oder eine PDA nicht verfügbar/kontraindiziert ist", uk:"Аналгезія ремифентанілом у режимі PCA, якщо я про неї попрошу або ЕДА недоступна/протипоказана", ru:"Анальгезия ремифентанилом в режиме PCA, если я об этом попрошу или ЭДА будет недоступна/противопоказана"},
"Brak zgody na petydynę (dolargan) i inne środki silnie zmieniające świadomość": {en:"No consent to pethidine (meperidine) or other strongly sedating opioids", de:"Keine Zustimmung zu Pethidin und anderen stark bewusstseinsverändernden Mitteln", uk:"Немає згоди на петидин (долярган) та інші засоби, що сильно змінюють свідомість", ru:"Нет согласия на петидин (меперидин) и другие сильнодействующие опиоиды, изменяющие сознание"},
"Preferuję ochronę krocza i uniknięcie nacięcia (epizjotomii), o ile nie ma wskazań": {en:"I prefer perineal protection and avoiding episiotomy, unless indicated", de:"Ich bevorzuge Dammschutz und die Vermeidung eines Dammschnitts (Episiotomie), sofern nicht indiziert", uk:"Надаю перевагу захисту промежини й уникненню розрізу (епізіотомії), якщо немає показань", ru:"Предпочитаю защиту промежности и избежание разреза (эпизиотомии), если нет показаний"},
"Nacięcie krocza tylko przy wyraźnych wskazaniach medycznych, po poinformowaniu": {en:"Episiotomy only with clear medical indication, after being informed", de:"Dammschnitt nur bei eindeutiger medizinischer Indikation, nach Information", uk:"Розріз промежини лише за чіткими медичними показаннями, після інформування", ru:"Разрез промежности только при чётких медицинских показаниях, после информирования"},
"Miejscowe znieczulenie przy ewentualnym zszywaniu krocza": {en:"Local anaesthesia if perineal stitching is needed", de:"Lokalanästhesie bei eventuellem Nähen des Damms", uk:"Місцеве знеболення при можливому накладанні швів на промежину", ru:"Местное обезболивание при возможном наложении швов на промежность"},
"Bez wywoływania porodu (w tym amniotomii), jeśli brak wyraźnych wskazań": {en:"No labour induction (including amniotomy) without clear indication", de:"Keine Geburtseinleitung (auch keine Amniotomie) ohne eindeutige Indikation", uk:"Без індукції пологів (включно з амніотомією), якщо немає чітких показань", ru:"Без индукции родов (включая амниотомию), если нет чётких показаний"},
"Najpierw próba metod naturalnych (ruch, aktywność), jeśli stan dziecka pozwala": {en:"Natural methods (movement, activity) tried first, if the baby's condition allows", de:"Zuerst Versuch natürlicher Methoden (Bewegung, Aktivität), sofern der Zustand des Kindes es erlaubt", uk:"Спочатку спроба природних методів (рух, активність), якщо стан дитини дозволяє", ru:"Сначала попытка естественных методов (движение, активность), если состояние ребёнка позволяет"},
"Jeśli indukcja konieczna — najpierw prostaglandyna, potem oksytocyna": {en:"If induction is necessary — prostaglandin first, then oxytocin", de:"Falls Einleitung nötig — zuerst Prostaglandin, dann Oxytocin", uk:"Якщо індукція необхідна — спочатку простагландин, потім окситоцин", ru:"Если индукция необходима — сначала простагландин, затем окситоцин"},
"Oksytocyna / amniotomia wyłącznie po wyjaśnieniu wskazań i mojej świadomej zgodzie": {en:"Oxytocin / amniotomy only after explanation of indications and my informed consent", de:"Oxytocin / Amniotomie nur nach Erklärung der Indikation und meiner informierten Zustimmung", uk:"Окситоцин / амніотомія лише після пояснення показань і моєї усвідомленої згоди", ru:"Окситоцин / амниотомия только после объяснения показаний и моего осознанного согласия"},
"Możliwość fizjologicznego urodzenia łożyska, jeśli brak czynników ryzyka krwotoku": {en:"Physiological delivery of the placenta, if no haemorrhage risk factors", de:"Physiologische Plazentageburt, sofern keine Blutungsrisikofaktoren vorliegen", uk:"Можливість фізіологічного народження плаценти, якщо немає факторів ризику кровотечі", ru:"Возможность физиологического рождения плаценты, если нет факторов риска кровотечения"},
"Profilaktyczne podanie oksytocyny w III okresie — po informacji, jeśli wskazane": {en:"Prophylactic oxytocin in the third stage — after being informed, if indicated", de:"Prophylaktische Oxytocingabe in der Nachgeburtsphase — nach Information, falls indiziert", uk:"Профілактичне введення окситоцину в третьому періоді — після інформування, якщо показано", ru:"Профилактическое введение окситоцина в третьем периоде — после информирования, если показано"},
"Urodzenie łożyska bez pośpiechu, jeśli stan matki i dziecka stabilny": {en:"Unhurried delivery of the placenta, if mother and baby are stable", de:"Unbeschleunigte Plazentageburt, sofern Mutter und Kind stabil sind", uk:"Народження плаценти без поспіху, якщо стан матері й дитини стабільний", ru:"Рождение плаценты без спешки, если состояние матери и ребёнка стабильно"},
"Uniknięcie cięcia, jeśli nie ma bezwzględnych wskazań": {en:"Avoiding a caesarean unless absolutely indicated", de:"Vermeidung eines Kaiserschnitts ohne zwingende Indikation", uk:"Уникнення кесаревого розтину, якщо немає абсолютних показань", ru:"Избежание кесарева сечения, если нет абсолютных показаний"},
"Dokładna informacja o powodach i moja świadoma zgoda (poza sytuacją nagłą)": {en:"A clear explanation of reasons and my informed consent (except in emergencies)", de:"Genaue Information über die Gründe und meine informierte Zustimmung (außer im Notfall)", uk:"Точна інформація про причини і моя усвідомлена згода (крім невідкладних ситуацій)", ru:"Точная информация о причинах и моё осознанное согласие (кроме экстренных ситуаций)"},
"Obecność osoby towarzyszącej podczas operacji, jeśli to możliwe": {en:"Support person present during surgery, if possible", de:"Anwesenheit der Begleitperson während der Operation, wenn möglich", uk:"Присутність особи супроводу під час операції, якщо можливо", ru:"Присутствие сопровождающего во время операции, если это возможно"},
"Kontakt skóra do skóry na sali operacyjnej, gdy stan dziecka i matki pozwala": {en:"Skin-to-skin contact in the operating room, when the condition of mother and baby allows", de:"Haut-zu-Haut-Kontakt im Operationssaal, wenn Zustand von Mutter und Kind es erlauben", uk:"Контакт шкіра до шкіри в операційній, коли стан матері та дитини дозволяє", ru:"Контакт кожа к коже в операционной, когда состояние ребёнка и матери позволяет"},
"Jeśli matka nie może — kontakt skóra do skóry z ojcem dziecka": {en:"If the mother cannot, skin-to-skin contact with the baby's father", de:"Falls die Mutter nicht kann — Haut-zu-Haut-Kontakt mit dem Vater des Kindes", uk:"Якщо мати не може — контакт шкіра до шкіри з батьком дитини", ru:"Если мать не может — контакт кожа к коже с отцом ребёнка"},
"Jak najszybsze przystawienie do piersi po cięciu": {en:"Breastfeeding as soon as possible after the caesarean", de:"Möglichst frühes Anlegen an die Brust nach dem Kaiserschnitt", uk:"Якнайшвидше прикладання до грудей після кесаревого розтину", ru:"Как можно более раннее прикладывание к груди после кесарева сечения"},
"Nieprzerwany kontakt skóra do skóry przez co najmniej 2 godziny po porodzie (także po cięciu cesarskim)": {en:"Uninterrupted skin-to-skin contact for at least 2 hours after birth (also after a caesarean)", de:"Ununterbrochener Haut-zu-Haut-Kontakt für mindestens 2 Stunden nach der Geburt (auch nach Kaiserschnitt)", uk:"Безперервний контакт шкіра до шкіри щонайменше 2 години після пологів (також після кесаревого розтину)", ru:"Непрерывный контакт кожа к коже не менее 2 часов после родов (также после кесарева сечения)"},
"Osuszenie zamiast kąpieli — pozostawienie mazi płodowej, bez kąpieli w pierwszej dobie": {en:"Drying instead of bathing — leaving vernix caseosa, no bath in the first 24 hours", de:"Abtrocknen statt Baden — Käseschmiere belassen, kein Bad am ersten Tag", uk:"Обсушування замість купання — залишення першородного мастила, без купання в першу добу", ru:"Обсушивание вместо купания — сохранение первородной смазки, без купания в первые сутки"},
"Ocena Apgar i wstępna ocena podczas kontaktu skóra do skóry, bez zbędnego rozdzielania": {en:"Apgar and initial assessment during skin-to-skin contact, without unnecessary separation", de:"Apgar-Bewertung und Erstuntersuchung während des Haut-zu-Haut-Kontakts, ohne unnötige Trennung", uk:"Оцінка за Апгар і первинний огляд під час контакту шкіра до шкіри, без зайвого розділення", ru:"Оценка по шкале Апгар и первичный осмотр во время контакта кожа к коже, без лишнего разделения"},
"Ważenie, mierzenie i badanie po zakończeniu pierwszego, nieprzerwanego kontaktu": {en:"Weighing, measuring and examination after the first uninterrupted contact ends", de:"Wiegen, Messen und Untersuchung nach Abschluss des ersten ununterbrochenen Kontakts", uk:"Зважування, вимірювання та огляд після завершення першого безперервного контакту", ru:"Взвешивание, измерение и осмотр после завершения первого непрерывного контакта"},
"Odroczone odpępnienie — co najmniej 60 sekund, optymalnie do ustania tętnienia": {en:"Delayed cord clamping — at least 60 seconds, ideally until pulsation stops", de:"Verzögertes Abnabeln — mindestens 60 Sekunden, optimal bis zum Sistieren der Pulsation", uk:"Відстрочене перетискання пуповини — щонайменше 60 секунд, оптимально до припинення пульсації", ru:"Отсроченное пересечение пуповины — не менее 60 секунд, оптимально до прекращения пульсации"},
"Przecięcie pępowiny przez ojca dziecka, jeśli będzie chciał i nie ma przeciwwskazań": {en:"Cord cutting by the baby's father, if he wishes and there are no contraindications", de:"Durchtrennen der Nabelschnur durch den Vater des Kindes, falls gewünscht und keine Gegenanzeigen bestehen", uk:"Перетискання пуповини батьком дитини, якщо він захоче і немає протипоказань", ru:"Пересечение пуповины отцом ребёнка, если он захочет и нет противопоказаний"},
"Pierwsze przystawienie do piersi jeszcze na sali porodowej, w trakcie kontaktu skóra do skóry": {en:"First breastfeeding still in the delivery room, during skin-to-skin contact", de:"Erstes Anlegen an die Brust noch im Kreißsaal, während des Haut-zu-Haut-Kontakts", uk:"Перше прикладання до грудей ще в пологовій залі, під час контакту шкіра до шкіри", ru:"Первое прикладывание к груди ещё в родильном зале, во время контакта кожа к коже"},
"Wsparcie położnej lub doradcy laktacyjnego w prawidłowym przystawieniu": {en:"Support from a midwife or lactation consultant with correct latching", de:"Unterstützung durch Hebamme oder Stillberaterin beim korrekten Anlegen", uk:"Підтримка акушерки або консультанта з лактації для правильного прикладання", ru:"Поддержка акушерки или консультанта по грудному вскармливанию для правильного прикладывания"},
"Dokarmianie wyłącznie na wskazanie lekarskie, z preferencją odciągniętej siary zamiast mleka modyfikowanego": {en:"Supplementary feeding only on medical indication, preferring expressed colostrum over formula", de:"Zufüttern nur auf ärztliche Indikation, mit Präferenz für abgepumptes Kolostrum statt Formulanahrung", uk:"Догодовування лише за медичними показаннями, з перевагою зцідженого молозива замість суміші", ru:"Докорм только по медицинским показаниям, с предпочтением сцеженного молозива вместо смеси"},
"Bez rutynowego podawania smoczka w okresie ustalania laktacji": {en:"No routine pacifier use while breastfeeding is being established", de:"Kein routinemäßiger Schnuller während der Stillanbahnung", uk:"Без рутинного використання пустушки в період налагодження лактації", ru:"Без рутинного использования соски-пустышки в период становления лактации"},
"Rooming-in całodobowy — bez rozdzielania mamy i dziecka bez wskazań medycznych": {en:"24-hour rooming-in — no separation of mother and baby without medical indication", de:"24-Stunden-Rooming-in — keine Trennung von Mutter und Kind ohne medizinische Indikation", uk:"Цілодобовий рухумінг — без розділення мами й дитини без медичних показань", ru:"Круглосуточное совместное пребывание — без разделения мамы и ребёнка без медицинских показаний"},
"Jeśli dziecko wymaga opieki neonatologicznej — prosimy, aby ojciec towarzyszył dziecku przez cały czas, gdy matka nie może": {en:"If the baby needs neonatal care, we ask that the father stay with the baby whenever the mother cannot", de:"Falls das Kind neonatologische Betreuung benötigt, bitten wir, dass der Vater das Kind begleitet, wann immer die Mutter nicht kann", uk:"Якщо дитині потрібна неонатальна допомога — просимо, щоб батько був поруч з дитиною весь час, коли мати не може", ru:"Если ребёнку нужна неонатальная помощь — просим, чтобы отец находился с ребёнком всё время, когда мать не может"},
"Prosimy o możliwie najwcześniejszy kontakt skóra do skóry (kangurowanie), gdy tylko stan dziecka na to pozwoli": {en:"Please allow skin-to-skin (kangaroo care) as early as possible once the baby's condition allows", de:"Wir bitten um möglichst frühen Haut-zu-Haut-Kontakt (Känguru-Methode), sobald der Zustand des Kindes es erlaubt", uk:"Просимо якнайшвидше забезпечити контакт шкіра до шкіри (кенгуру), щойно стан дитини дозволить", ru:"Просим обеспечить контакт кожа к коже (метод кенгуру) как можно раньше, как только состояние ребёнка позволит"},
"Prosimy o wsparcie w rozpoczęciu odciągania pokarmu w pierwszych godzinach po porodzie, nawet gdy dziecko nie może jeszcze jeść": {en:"Please support us in starting to express milk in the first hours after birth, even if the baby cannot yet feed", de:"Wir bitten um Unterstützung beim Beginn des Abpumpens in den ersten Stunden nach der Geburt, auch wenn das Kind noch nicht trinken kann", uk:"Просимо допомогти розпочати зціджування молока в перші години після пологів, навіть якщо дитина ще не може їсти", ru:"Просим помочь начать сцеживание молока в первые часы после родов, даже если ребёнок ещё не может есть"},
"Prosimy o karmienie dziecka mlekiem matki, a przy jego braku — mlekiem z banku mleka kobiecego, jeśli jest dostępne": {en:"Please feed the baby the mother's milk, or if unavailable, donor milk from a milk bank, if available", de:"Wir bitten, das Kind mit Muttermilch zu füttern, ersatzweise mit Spenderinnenmilch aus einer Frauenmilchbank, falls verfügbar", uk:"Просимо годувати дитину молоком матері, а за його відсутності — донорським молоком з банку молока, якщо доступне", ru:"Просим кормить ребёнка молоком матери, а при его отсутствии — донорским молоком из банка молока, если доступно"},
"Prosimy o bieżące informowanie obojga rodziców o stanie dziecka i planie leczenia": {en:"Please keep both parents continuously informed of the baby's condition and treatment plan", de:"Wir bitten um laufende Information beider Elternteile über den Zustand des Kindes und den Behandlungsplan", uk:"Просимо постійно інформувати обох батьків про стан дитини та план лікування", ru:"Просим постоянно информировать обоих родителей о состоянии ребёнка и плане лечения"},
"Prosimy o umożliwienie rodzicom udziału w pielęgnacji dziecka w zakresie, na jaki pozwala jego stan": {en:"Please allow parents to take part in the baby's care to the extent his/her condition permits", de:"Wir bitten, den Eltern die Teilnahme an der Pflege des Kindes zu ermöglichen, soweit der Zustand es zulässt", uk:"Просимо дозволити батькам брати участь у догляді за дитиною наскільки дозволяє її стан", ru:"Просим предоставить родителям возможность участвовать в уходе за ребёнком в той мере, в какой позволяет его состояние"},
"Bankowanie krwi pępowinowej — zestaw pobraniowy i dokumentację przywieziemy ze sobą i przekażemy przy przyjęciu": {en:"Cord blood banking — we will bring the collection kit and paperwork and hand it over on admission", de:"Nabelschnurblut-Banking — wir bringen das Entnahmeset und die Unterlagen mit und übergeben sie bei der Aufnahme", uk:"Банкування пуповинної крові — комплект для забору та документацію привеземо самі й передамо при поступленні", ru:"Банкирование пуповинной крови — набор для забора и документацию привезём с собой и передадим при поступлении"},
"Priorytet: opóźnione odpępnienie ważniejsze niż objętość pobranej krwi; przy zagrożeniu rezygnujemy z pobrania": {en:"Priority: delayed cord clamping matters more than the volume of blood collected; we forgo collection if there is any risk", de:"Priorität: verzögertes Abnabeln ist wichtiger als die Menge des entnommenen Blutes; bei Risiko verzichten wir auf die Entnahme", uk:"Пріоритет: відстрочене перетискання пуповини важливіше за обсяг зібраної крові; за наявності ризику відмовляємось від забору", ru:"Приоритет: отсроченное пересечение пуповины важнее объёма забранной крови; при угрозе отказываемся от забора"},
"Witamina K — podanie domięśniowe (preferowane, najwyższa skuteczność)": {en:"Vitamin K — intramuscular administration (preferred, highest effectiveness)", de:"Vitamin K — intramuskuläre Gabe (bevorzugt, höchste Wirksamkeit)", uk:"Вітамін K — внутрішньом'язове введення (пріоритетно, найвища ефективність)", ru:"Витамин K — внутримышечное введение (предпочтительно, наивысшая эффективность)"},
"Witamina K — podanie doustne (alternatywa, jeśli wybrana)": {en:"Vitamin K — oral administration (alternative, if chosen)", de:"Vitamin K — orale Gabe (Alternative, falls gewählt)", uk:"Вітамін K — пероральне введення (альтернатива, якщо обрано)", ru:"Витамин K — пероральное введение (альтернатива, если выбрано)"},
"Wyrażamy zgodę na wszystkie badania przesiewowe (test z piętki, pulsoksymetria, badanie słuchu) — w miarę możliwości w naszej obecności": {en:"We consent to all screening tests (heel-prick test, pulse oximetry, hearing screening) — in our presence where possible", de:"Wir stimmen allen Screening-Untersuchungen zu (Fersenblut-Test, Pulsoxymetrie, Hörscreening) — nach Möglichkeit in unserer Anwesenheit", uk:"Даємо згоду на всі скринінгові обстеження (аналіз крові з п'яти, пульсоксиметрія, скринінг слуху) — за можливості в нашій присутності", ru:"Даём согласие на все скрининговые обследования (анализ крови из пятки, пульсоксиметрия, скрининг слуха) — по возможности в нашем присутствии"},
"Profilaktyka zakażeń oczu — zgodnie z wynikiem badań matki (przy wyniku ujemnym akceptujemy odstąpienie)": {en:"Eye infection prophylaxis — according to the mother's test results (we accept omitting it if the result is negative)", de:"Augeninfektionsprophylaxe — gemäß dem Testergebnis der Mutter (bei negativem Ergebnis akzeptieren wir den Verzicht)", uk:"Профілактика інфекцій очей — відповідно до результатів аналізів матері (за негативного результату погоджуємось на відмову)", ru:"Профилактика инфекций глаз — в соответствии с результатами анализов матери (при отрицательном результате согласны на отказ)"},
"Prosimy o informację o każdym leku lub suplemencie podawanym dziecku": {en:"Please inform us of every medication or supplement given to the baby", de:"Wir bitten um Information über jedes dem Kind verabreichte Medikament oder Präparat", uk:"Просимо інформувати про кожен препарат або добавку, що вводиться дитині", ru:"Просим информировать о каждом лекарстве или добавке, вводимой ребёнку"},
"Szczepienia realizujemy we własnym zakresie — na obecnym etapie nie wyrażamy zgody na szczepienia w szpitalu (WZW B, BCG); wykonamy je po wypisie u wybranego pediatry. Odroczenie WZW B przy potwierdzonym ujemnym wyniku HBsAg u matki jest bezpieczne.": {en:"We will arrange vaccinations ourselves — at this stage we do not consent to in-hospital vaccination (hepatitis B, BCG); we will have them done after discharge by our chosen paediatrician. Delaying the hepatitis B vaccine is safe when the mother's HBsAg result is confirmed negative.", de:"Wir organisieren die Impfungen selbst — derzeit stimmen wir Impfungen im Krankenhaus (Hepatitis B, BCG) nicht zu; wir lassen sie nach der Entlassung bei unserem Kinderarzt durchführen. Der Aufschub der Hepatitis-B-Impfung ist bei bestätigt negativem HBsAg-Ergebnis der Mutter sicher.", uk:"Щеплення робимо самостійно — на цьому етапі не даємо згоди на щеплення в лікарні (гепатит B, БЦЖ); зробимо їх після виписки в обраного педіатра. Відкладення щеплення від гепатиту B безпечне за підтвердженого негативного результату HBsAg у матері.", ru:"Прививки делаем самостоятельно — на данном этапе не даём согласия на прививки в больнице (гепатит B, БЦЖ); сделаем их после выписки у выбранного педиатра. Отсрочка прививки от гепатита B безопасна при подтверждённом отрицательном результате HBsAg у матери."},
"Wyrażamy zgodę na szczepienia w szpitalu (WZW B, BCG) zgodnie ze standardem, w obecności rodzica": {en:"We consent to in-hospital vaccination (hepatitis B, BCG) per standard practice, with a parent present", de:"Wir stimmen Impfungen im Krankenhaus (Hepatitis B, BCG) gemäß Standard zu, in Anwesenheit eines Elternteils", uk:"Даємо згоду на щеплення в лікарні (гепатит B, БЦЖ) згідно зі стандартом, у присутності одного з батьків", ru:"Даём согласие на прививки в больнице (гепатит B, БЦЖ) согласно стандарту, в присутствии родителя"},
"Prosimy o salę rodzinną (w miarę dostępności)": {en:"Please provide a family room (subject to availability)", de:"Wir bitten um ein Familienzimmer (nach Verfügbarkeit)", uk:"Просимо сімейну палату (за наявності)", ru:"Просим семейную палату (при наличии)"},
"Chcemy skorzystać z usługi hotelowej — nocleg ojca dziecka przy mamie i noworodku": {en:"We would like to use the hotel service — overnight stay for the baby's father with mother and newborn", de:"Wir möchten den Hotelservice nutzen — Übernachtung des Vaters bei Mutter und Neugeborenem", uk:"Хочемо скористатись готельною послугою — ночівля батька дитини разом з мамою і новонародженим", ru:"Хотим воспользоваться гостиничной услугой — ночлег отца ребёнка рядом с мамой и новорождённым"},
"Jestem doświadczoną mamą — samodzielna opieka nad dzieckiem przy wsparciu personelu": {en:"I am an experienced mother — independent baby care with staff support available", de:"Ich bin eine erfahrene Mutter — selbstständige Versorgung des Kindes mit Unterstützung des Personals", uk:"Я досвідчена мама — самостійний догляд за дитиною за підтримки персоналу", ru:"Я опытная мама — самостоятельный уход за ребёнком при поддержке персонала"},
"Rooming-in 24 h, bez separacji bez wskazań medycznych": {en:"24-hour rooming-in, no separation without medical indication", de:"24-Stunden-Rooming-in, keine Trennung ohne medizinische Indikation", uk:"Рухумінг 24 години, без розділення без медичних показань", ru:"Совместное пребывание 24 часа, без разделения без медицинских показаний"},
"Wszystkie czynności i badania dziecka w obecności matki lub ojca": {en:"All the baby's procedures and examinations in the presence of the mother or father", de:"Alle Maßnahmen und Untersuchungen des Kindes in Anwesenheit von Mutter oder Vater", uk:"Усі процедури та обстеження дитини в присутності матері або батька", ru:"Все процедуры и обследования ребёнка в присутствии матери или отца"},
"Wsparcie laktacyjne w czasie całego pobytu": {en:"Lactation support throughout the hospital stay", de:"Stillunterstützung während des gesamten Aufenthalts", uk:"Підтримка лактації протягом усього перебування", ru:"Поддержка грудного вскармливания на протяжении всего пребывания"},
"Prosimy o informację o zakresie danych przekazywanych podmiotom zewnętrznym w związku z opieką nad dzieckiem": {en:"Please inform us what data is shared with external parties in connection with the baby's care", de:"Wir bitten um Information über den Umfang der an externe Stellen weitergegebenen Daten im Zusammenhang mit der Versorgung des Kindes", uk:"Просимо інформувати про обсяг даних, що передаються зовнішнім установам у зв'язку з доглядом за дитиною", ru:"Просим информировать об объёме данных, передаваемых внешним организациям в связи с уходом за ребёнком"},
"Wypis do domu możliwie szybko, jeśli stan matki i dziecka jest dobry": {en:"Discharge home as soon as possible, if mother and baby are both well", de:"Möglichst frühe Entlassung nach Hause, sofern Mutter und Kind wohlauf sind", uk:"Виписка додому якнайшвидше, якщо стан матері й дитини добрий", ru:"Выписка домой как можно быстрее, если состояние матери и ребёнка хорошее"}
  };

  global.PNM_I18N = { steps: STEP_TITLES, uiSteps: UI_STEP_TITLES, ui: UI, pdf: PDF_STATIC, values: VALUES, rowLabels: ROW_LABELS,
    t: function (pl, lang) { // tłumaczy pojedynczą frazę; brak wpisu -> zwraca polski oryginał
      if (!lang || lang === 'pl') return pl;
      var e = VALUES[pl];
      return (e && e[lang]) ? e[lang] : pl;
    },
    // Na żywo tłumaczy widoczną treść kreatora w DOM: nagłówki kroków, opisy, etykiety pól,
    // placeholdery, przyciski, strefy zakupu/pobrania.
    // Nie rusza atrybutu value="" (dane kreatora pozostają kanoniczne po polsku).
    applyToKreator: function (lang) {
      var root = document.getElementById('kreator');
      if (!root) return;
      lang = lang || 'pl';
      var TXT = (global.PNM_I18N && global.PNM_I18N.txt) || {};

      // Zapamiętuje oryginał PL raz, żeby przełączanie tam i z powrotem było bezstratne.
      function orig(el, prop, getter) {
        var key = 'plOrig' + prop;
        if (el.dataset[key] === undefined) el.dataset[key] = getter();
        return el.dataset[key];
      }
      function tx(pl) {
        if (lang === 'pl') return pl;
        var e = TXT[pl];
        return (e && e[lang]) ? e[lang] : pl;
      }

      // 1) Nagłówki H3 kroków (osobna tablica, inna niż tytuły sekcji PDF)
      root.querySelectorAll('.creator-step h3, [data-step] h3').forEach(function (h) {
        var pl = orig(h, 'Txt', function () { return h.textContent.trim(); });
        var idx = UI_STEP_TITLES.pl.indexOf(pl);
        h.textContent = (idx > -1 && UI_STEP_TITLES[lang]) ? UI_STEP_TITLES[lang][idx] : tx(pl);
      });

      // 2) Etykiety opcji (span obok input w <label>) — klucz słownika to ZAWSZE input.value
      //    (pełne zdanie kliniczne); span pokazuje skróconą etykietę PL, przy tłumaczeniu
      //    pokazujemy pełne, precyzyjne zdanie (dłuższe, ale poprawne merytorycznie).
      var optionSpans = [];
      root.querySelectorAll('label > input[value]').forEach(function (inp) {
        var span = inp.nextElementSibling;
        if (!span) return;
        optionSpans.push(span);
        var plShort = orig(span, 'Txt', function () { return span.textContent; });
        var plFull = inp.value;
        if (lang === 'pl') { span.textContent = plShort; return; }
        span.textContent = (VALUES[plFull] && VALUES[plFull][lang]) ? VALUES[plFull][lang] : tx(plShort);
      });

      // 3) Pozostałe teksty statyczne — tłumaczymy pojedyncze WĘZŁY TEKSTOWE, nie całe elementy.
      //    Dzięki temu działają też etykiety z zagnieżdżonym <span> (np. „Imię i nazwisko rodzącej *”)
      //    i nie niszczymy struktury HTML wewnątrz akapitów.
      if (!root.__pnmTextNodes) {
        var nodes = [];
        var walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
          acceptNode: function (n) {
            if (!n.nodeValue || !n.nodeValue.trim()) return NodeFilter.FILTER_REJECT;
            var pEl = n.parentElement;
            if (!pEl) return NodeFilter.FILTER_REJECT;
            var tag = pEl.tagName;
            if (tag === 'SCRIPT' || tag === 'STYLE' || tag === 'OPTION') return NodeFilter.FILTER_REJECT;
            // treść generowana w JS ma własną ścieżkę tłumaczenia
            if (pEl.closest('#summaryBox, #planPreview')) return NodeFilter.FILTER_REJECT;
            if (optionSpans.indexOf(pEl) > -1) return NodeFilter.FILTER_REJECT;
            return NodeFilter.FILTER_ACCEPT;
          }
        });
        var nd;
        while ((nd = walker.nextNode())) nodes.push({ node: nd, pl: nd.nodeValue });
        root.__pnmTextNodes = nodes;
      }
      root.__pnmTextNodes.forEach(function (rec) {
        var pEl = rec.node.parentElement;
        if (!pEl) return;
        // nagłówki kroków i etykiety opcji obsłużone wcześniej — nie ruszamy ich ponownie
        if (pEl.tagName === 'H3' || optionSpans.indexOf(pEl) > -1) return;
        if (lang === 'pl') { rec.node.nodeValue = rec.pl; return; }
        var key = rec.pl.trim();
        if (!key) return;
        var t = TXT[key];
        if (t && t[lang]) rec.node.nodeValue = rec.pl.replace(key, t[lang]);
      });

      // 4) Placeholdery pól tekstowych
      root.querySelectorAll('input[placeholder], textarea[placeholder]').forEach(function (el) {
        var pl = orig(el, 'Ph', function () { return el.placeholder; });
        el.placeholder = (lang === 'pl') ? pl : tx(pl.trim());
      });

      // 5) Przyciski nawigacji i pobierania (własny słownik UI, ma pierwszeństwo)
      var map = {prevBtn: 'back', nextBtn: 'next', dlBtn: 'download'};
      Object.keys(map).forEach(function (id) {
        var el = document.getElementById(id);
        if (!el) return;
        var pl = orig(el, 'Txt', function () { return el.textContent.trim(); });
        el.textContent = (lang === 'pl') ? pl : ((UI[lang] && UI[lang][map[id]]) || tx(pl));
      });

      // 6) Etykieta postępu i licznik kroków — przerysowywane przez showStep()
      if (typeof global.PNM_refreshProgress === 'function') { try { global.PNM_refreshProgress(); } catch (e) {} }

      document.documentElement.setAttribute('data-kreator-lang', lang);
      try { localStorage.setItem('pnm_kreator_lang', lang); } catch (e) {}
    }
  };
})(window);
